const
  gsTaurusTLSVersionMajor = 1;
  {$NODEFINE gsTaurusTLSVersionMajor}
  gsTaurusTLSVersionMinor = 0;
  {$NODEFINE gsTaurusTLSVersionMinor}
  gsTaurusTLSVersionRelease = 0;
  {$NODEFINE gsTaurusTLSVersionRelease}
  gsTaurusTLSVersionBuild = 11;
  {$NODEFINE gsTaurusTLSVersionBuild}

  (*$HPPEMIT '#define gsTaurusTLSVersionMajor 1'*)
  (*$HPPEMIT '#define gsTaurusTLSVersionMinor 0'*)
  (*$HPPEMIT '#define gsTaurusTLSVersionRelease 0'*)
  (*$HPPEMIT '#define gsTaurusTLSVersionBuild 11'*)
  (*$HPPEMIT ''*)

  gsTaurusTLSVersion = '1.0.0.11'; {do not localize}
  gsTaurusTLSProductName = 'TaurusTLS';  {do not localize}
  gsTaurusTLSProductVersion = '1.0.0.11'; {do not localize}
